font_path:
    - ./assets/fonts/

#pinproc_class: procgame.fakepinproc.FakePinPROC # comment out this line when using a real P-ROC. 

desktop_dmd_scale: 5                # the dmd scale is the multiplier per dot.  At 5 each dot is 5x5 pixels

keyboard_switch_map:                                # this is the mapping of keyboard keys to switch matrix keys, for K_* constants, see https://www.pygame.org/docs/ref/key.html#module-pygame.key
    1: S81 # trough1
    2: S82 # trough2
    3: S83 # trough3
    4: S84 # trough4
    5: S85 # trough5
    6: S86 # trough6
    K_UP: SD5 # exit
    K_LEFT: SD6 # down
    K_RIGHT: SD7 # up
    K_DOWN: SD8 # enter
    a: S44 # superGame
    s: S13 # startButton
    j: S54 # J
    u: S55 # U
    d: S56 # D
    g: S57 # G
    e: S58 # E
    p: S74 # popperR
    9: S14 # tilt
    0: S21 # slam tilt
    K_LSHIFT: SF4 # flipperLwL
    K_RSHIFT: SF2 # flipperLwR
    K_CAPSLOCK: S11 # fireL
    K_RETURN: S12 # fireR
    K_TAB: S73 # popperL
    K_BACKSPACE: S74 # popperR
    '[': S64 # leftRampExit
    ']': S66 # centerRampExit
    K_BACKSLASH: S76 # rightRampExit
    'l': S33 # leftRollover
    ';': S35 # topCenterRollover
    "'": S72 # topRightOpto
    z: S15 # shooterL
    '/': S41 # shooterR
    '.': S68 # captiveBall3
    x: S27 # mystery
    q: S36 # leftScorePost

    