font_path:
    - ./assets/fonts/
config_path:
    - ./config
dmd_path: ./assets/dmd/
sound_path: ./assets/sound/
voice_dir: voice/ # i.e., this is assets/sound/voice/
sfx_dir: sfx/
music_dir: music/
hdfont_path: ./assets/fonts/

default_modes:  # these are the default provided modes by SkeletonGame; turn them off here.
    attract: False
    score_display: True
    bonus_tally: False
    osc_input: False
    service_mode: False
    tilt_mode: True
    ball_search: True
    ball_search_delay: 15

pinproc_class: procgame.fakepinproc.FakePinPROC # comment out this line when using a real P-ROC. 

# all of this is for the DMD
proc_dmd: True                     # whether the physical monochrome DMD driven by the P-ROC is enabled
dmd_grid_path: ./assets/dmd/        # where to find the dmdgrid32x32.png file
dmd_dots_w: 128                     # the display width in virtual dots
dmd_dots_h: 32                     # the display height in virtual donts
dmd_dot_filter: True                # enable to virtual dot effect; false disables dot separation
dmd_fullscreen: False               # Full-screen mode scales the contents to fit the full display; may not look right
desktop_dmd_scale: 5                # the dmd scale is the multiplier per dot.  At 5 each dot is 5x5 pixels
dmd_framerate: 30
screen_position_x: 123              # an offset for where the window should be located on launch -- 1366x768 is me, so
screen_position_y: 104              # 224*5x112*5 = 1120x560; the difference is 246x208 hence the offsets 123x104
dmd_window_border: True             # show a window border?  In the machine, go without it, and with black wallpaper

PYSDL2_DLL_PATH: c:\P-ROC\DLLs\ # where to find the sdl2.dll

vp_game_map_file: /P-ROC/shared/vp_game_map.yaml  # relevant for Visual Pinball (only)

keyboard_switch_map:    # this is the mapping of keyboard keys to switch matrix keys, for constants, see python module sdl2.keycode
    1: S81 # trough1
    2: S82 # trough2
    3: S83 # trough3
    4: S84 # trough4
    5: S85 # trough5
    6: S86 # trough6
    UP: SD5 # exit
    LEFT: SD6 # down
    RIGHT: SD7 # up
    DOWN: SD8 # enter
    LSHIFT+s: S44 # superGame
    s: S13 # startButton
    j: S54 # J
    u: S55 # U
    d: S56 # D
    g: S57 # G
    e: S58 # E
    p: S74 # popperR
    9: S14 # tilt
    0: S21 # slam tilt
    LSHIFT: SF4 # flipperLwL
    RSHIFT: SF2 # flipperLwR
    CAPSLOCK: S11 # fireL
    RETURN: S12 # fireR
    TAB: S73 # popperL
    BACKSPACE: S74 # popperR
    '[': S64 # leftRampExit
    ']': S66 # centerRampExit
    BACKSLASH: S76 # rightRampExit
    'l': S33 # leftRollover
    ';': S35 # topCenterRollover
    "'": S72 # topRightOpto
    z: S15 # shooterL
    '/': S41 # shooterR
    '.': S31 # buyIn
    ',': S68 # captiveBall3
    x: S27 # mystery
    q: S36 # leftScorePost
    w: S37 # subwayEnter1
