Audits: {Avg Ball Time: '0:00', Avg Extra Balls: 0, Avg Game Time: '0:00', Avg Score: 0,
  Balls Played: 0, Games Played: 0, Games Started: 0}
BlocksHighScores:
- {date: 'Sun Oct  3 17:38:46 2010', inits: JTW, score: 8}
ClassicHighScores:
- {date: 'Sun Oct  3 17:38:46 2010', inits: GSS, score: 500000}
- {date: 'Sun Oct  3 17:44:49 2010', inits: ASP, score: 400000}
- {date: 'Sun Oct  3 16:22:47 2010', inits: JRP, score: 300000}
- {date: 'Sun Oct  3 15:04:27 2010', inits: JAT, score: 200000}
- {date: 'Sun Oct  3 22:05:01 2010', inits: CAP, score: 100000}
InnerLoopsHighScores:
- {date: 'Sun Oct  3 17:38:46 2010', inits: GSS, score: 2}
OuterLoopsHighScores:
- {date: 'Sun Oct  3 17:38:46 2010', inits: ASP, score: 2}
SuperGameHighScores:
- {date: 'Sun Oct  3 17:38:46 2010', inits: GSS, score: 2500000}
- {date: 'Sun Oct  3 17:44:49 2010', inits: ASP, score: 2000000}
- {date: 'Sun Oct  3 16:22:47 2010', inits: JRP, score: 1500000}
- {date: 'Sun Oct  3 15:04:27 2010', inits: JAT, score: 1000000}
- {date: 'Sun Oct  3 22:05:01 2010', inits: CAP, score: 500000}
