Coils: {popperL: 25}
Gameplay: {Block War ballsave time: 16, Block difficulty: medium, Blocks for Ultimate Challenge: 16,
  Celebration ballsave time: 20, Chain feature difficulty: medium, Death ballsave time: 20,
  Fear ballsave time: 10, Mortis ballsave time: 10, Multiball ballsave time: 20, Mystery ballsave time: 10,
  Mystery feature add time: 10, New ball ballsave time: 10, New ball repeating ballsave: false,
  Time for Death: 180, Time for Death shot: 10, Time for Fear shot: 25, Time for Hurry Up: 10,
  Time per chain feature: 30, Video mode: enemies}
Machine: {Allow restarts: true, Balls Per Game: 3, Deadworld Mod Installed: false,
  Max extra balls lit: 99, Max extra balls per game: 99, Number of tilt warnings: 2}
Replay: {Replay Award: Credit, Replay Boost: 200000, Replay Level 1: 500000, Replay Level 2: 1000000,
  Replay Level 3: 1500000, Replay Level 4: 2000000, Replay Levels: 1, Replay Percentage: 10,
  Replay Type: auto}
Sound: {Initial volume: 5}
