Machine (Standard):
  'Balls Per Game':
    options: [1,10]
    increments: 1
    default: 3
  'Quick Bonus Mode':
    options: [False,True]
    default: True
  'Attract Mode Sounds':
    options: ['On','Off']
    default: 'Off'
  'Attract Mode Music':
    options: ['On','Off']
    default: 'Off'
Machine (Coils):
  'Auto Plunger':
    options: [24,63]
    increments: 1
    default: 32
Sound:
  'Initial volume':
    options: [0,10]
    increments: 1
    default: 5
  'Music volume offset':
    options: [-0.4,-0.3,-0.2,-0.1,0,0.1,0.2,0.3,0.4]
    default: 0
Gameplay (Feature):
  'Skillshot Autoplunge Timer':
    options: [0,30]
    increments: 1
    default: 15
  'Ball Save Timer':
    options: [0,20]
    increments: 1
    default: 10





Machine:
  'Deadworld mod installed':
    options: [true, false]
    default: false
  'Initial volume':
    options: [1,20]
    increments: 1
    default: 10
  'Music volume offset':
    options: [-9,9]
    increments: 1
    default: 0
Display:
  'Left side score justify':
    options: [left, right]
    default: 'left'
Replay:
  'Replay Type':
    options: ['none','auto','fixed','incremental']
    default: 'auto'
  'Replay Percentage':
    options: [5,50]
    increments: 1
    default: 10
  'Replay Award':
    options: ['Credit', 'Extra Ball']
    default: 'Credit'
  'Replay Levels':
    options: [1,2,3,4]
    default: 1
  'Replay Level 1':
    options: [50000,10000000]
    increments: 50000
    default: 500000
  'Replay Level 2':
    options: [50000,10000000]
    increments: 50000
    default: 1000000
  'Replay Level 3':
    options: [50000,10000000]
    increments: 50000
    default: 1500000
  'Replay Level 4':
    options: [50000,10000000]
    increments: 50000
    default: 2000000
  'Replay Boost':
    options: [50000,10000000]
    increments: 50000
    default: 200000
Gameplay:
  'Number of tilt warnings':
    options: [0,10]
    increments: 1
    default: 2
  'Allow restarts':
    options: [true, false]
  'Balls per game':
    options: [1,10]
    increments: 1
    default: 3
  'Max extra balls per game':
    options: [0,1,2,3,4,5,6,7,8,9,99]
    default: 99
  'Max extra balls lit':
    options: [0,1,2,3,4,5,6,7,8,9,99]
    default: 99
  'New ball ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 10
  'New ball repeating ballsave':
    options: [false, true]
  'Multiball ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 20
  'Block War ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 15
  'Time per chain feature':
    options: [25,30,35,40,45]
    default: 30
  'Chain feature difficulty':
    options: ['easy', 'medium', 'hard']
    default: 'medium'
  'Time for Hurry Up':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 10
  'Block difficulty':
    options: ['easy', 'medium', 'hard']
    default: 'medium'
  'Blocks for Ultimate Challenge':
    options: [8,12,16]
    default: 16
  'Mystery ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 10
  'Mystery feature add time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 10
  'Video mode':
    options: ['enemies', 'cows', 'off']
  'Time for Fear shot':
    options: [10,15,20,25,30,35,40,45]
    default: 25
  'Fear ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 10
  'Mortis ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 10
  'Time for Death':
    options: [150,160,170,180,190,200]
    default: 180
  'Death ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 20
  'Time for Death shot':
    options: [5,6,7,8,9,10,15,20,25,30]
    default: 10
  'Celebration ballsave time':
    options: [5,6,7,8,9,10,11,12,13,14,15,20,25,30]
    default: 20
