# This file is a template for all of the settings used in the game.  The game code will
# load this file along with a user_settings.yaml file.  Any settings not present in
# the user_settings.yaml file will default to the default value specified here.  When
# any setting is saved (via the in-game service menu), the user_settings.yaml file
# will be updated with ALL of the entries here without overwriting existing settings.

Machine:
  'Deadworld mod installed':
    options: [true, false]
    default: false
  'Initial volume':
    options: [1,20]
    increments: 1
    default: 10
  'Music volume offset':
    options: [-9,9]
    increments: 1
    default: 0
Display:
  'Left side score justify':
    # This example has no default.  The first option (right) will be used as the default.
    options: [right, left]
Replay:
  'Replay Type':
    options: ['none','auto','fixed','incremental']
    default: 'auto'
  'Replay Percentage':
    options: [5,50]
    increments: 1
    default: 10
  'Replay Award':
    options: ['Credit', 'Extra Ball']
    default: 'Credit'
  'Replay Levels':
    options: [1,2,3,4]
    default: 1
  'Replay Level 1':
    options: [50000,10000000]
    increments: 50000
    default: 500000
  'Replay Level 2':
    options: [50000,10000000]
    increments: 50000
    default: 1000000
  'Replay Level 3':
    options: [50000,10000000]
    increments: 50000
    default: 1500000
  'Replay Level 4':
    options: [50000,10000000]
    increments: 50000
    default: 2000000
  'Replay Boost':
    options: [50000,10000000]
    increments: 50000
    default: 200000
Gameplay:
  'Number of tilt warnings':
    options: [0,10]
    increments: 1
    default: 2
  'Allow restarts':
    options: [true, false]
  'Balls per game':
    options: [1,10]
    increments: 1
    default: 3
  'Max extra balls per game':
    options: [0,1,2,3,4,5,99]
    default: 99
  'Max extra balls lit':
    options: [0,1,2,3,4,5,99]
    default: 99
  'New ball ballsave time':
    options: [6,8,10,12,15]
    default: 10
  'New ball repeating ballsave':
    options: [false, true]
  'Multiball ballsave time':
    options: [5,10,15,20,25,30,35]
    default: 20
  'Block War ballsave time':
    options: [5,10,15,20,25,30]
    default: 15
  'Time per chain feature':
    options: [25,30,35,40,45]
    default: 30
  'Chain feature difficulty':
    options: ['easy', 'medium', 'hard']
    default: 'medium'
  'Block difficulty':
    options: ['easy', 'medium', 'hard']
    default: 'medium'
  'Blocks for Ultimate Challenge':
    options: [8,12,16]
    default: 16
  'Video mode':
    options: ['enemies', 'cows', 'off']
  'Time for Fear shot':
    options: [10,15,20,25,30,35,40,45]
    default: 25
  'Fear ballsave time':
    options: [5,6,7,8,9,10,15,20,25,30]
    default: 10
  'Mortis ballsave time':
    options: [5,6,7,8,9,10,15,20,25,30]
    default: 10
  'Time for Death':
    options: [150,160,170,180,190,200]
    default: 180
  'Death ballsave time':
    options: [5,6,7,8,9,10,15,20,25,30]
    default: 20
  'Time for Death shot':
    options: [5,6,7,8,9,10,15,20,25,30]
    default: 10
  'Celebration ballsave time':
    options: [5,6,7,8,9,10,15,20,25,30]
    default: 20
    
 